add workflows (#32): stg
ci/cd

diff --git a/Taskfile.yaml b/Taskfile.yaml
--- a/Taskfile.yaml
+++ b/Taskfile.yaml
@@ -66,6 +66,7 @@ tasks:
       - _go/version/check
       - go/generate/dynamo
       - go/generate/openapi
+      - go/generate/openapispec
     cmds:
       - |
         if [ -d "{{.git_root}}/vendor" ]; then
@@ -93,6 +94,7 @@ tasks:
     dir: "{{.git_root}}"
     deps:
       - _go/install/lint
+      - _go/mod/vendor 
     cmds: 
       - "{{.go_root}}/bin/golangci-lint run cmd/... -v --timeout=15m"
   
@@ -141,6 +143,12 @@ tasks:
     internal: true
     silent: true
 
+  go/run/tests:
+    desc: Tests 
+    dir: "{{ .git_root }}" 
+    cmd: echo "Hello"
+    silent: true
+
   go/run/imports:
     desc: Run 'goimports'.
     dir: "{{ .git_root }}"
@@ -185,17 +193,39 @@ tasks:
     cmd: trivy repository {{.git_root}}
     silent: true
 
+  # docker/build/func:
+  #   desc: Run 'docker build' for 'FUNC=...' argument.
+  #   dir: "{{.git_root}}"
+  #   deps:
+  #     - _go/mod/vendor
+  #   vars:
+  #     FUNC_NAME: '{{ .FUNC }}'
+  #   cmds:
+  #     - docker build -t {{.api_image_name}}:{{.FUNC_NAME }} --build-arg FUNC_NAME={{.FUNC_NAME}} --build-arg GO_VERSION={{.go_version}} .
+  #   silent: true
+  
   docker/build/func:
-    desc: Run 'docker build' for 'FUNC=...' argument.
+    desc: Build single-function image
     dir: "{{.git_root}}"
     deps:
       - _go/mod/vendor
     vars:
       FUNC_NAME: '{{ .FUNC }}'
+      IMAGE_ARCH: '{{ .ARCH | default ARCH }}'
     cmds:
-      - docker build -t {{.api_image_name}}:{{.FUNC_NAME }} --build-arg FUNC_NAME={{.FUNC_NAME}} --build-arg GO_VERSION={{.go_version}} .
+      - docker buildx create --name applingo-builder --driver docker-container --use || true
+      - |
+        docker buildx build \
+          --builder applingo-builder \
+          --platform linux/{{.IMAGE_ARCH}} \
+          -t {{.api_image_name}}:{{.FUNC_NAME}} \
+          --build-arg FUNC_NAME={{.FUNC_NAME}} \
+          --build-arg GO_VERSION={{.go_version}} \
+          --cache-from type=gha \
+          --cache-to type=gha,mode=max \
+          --load .
     silent: true
-  
+
   _docker/build/all:
     desc: Run 'docker build' for all funcs.
     dir: "{{.git_root}}"
@@ -213,8 +243,19 @@ tasks:
     silent: true
     internal: true
   
+  docker/builds/func:
+    desc: Build single-function image for ARM64
+    dir: "{{.git_root}}"
+    deps:
+      - _go/mod/vendor
+    vars:
+      FUNC_NAME: '{{ .FUNC }}'
+    cmds:
+      - docker buildx build --builder applingo-builder --platform linux/arm64 -t applingo-images:{{.FUNC_NAME}} --build-arg FUNC_NAME={{.FUNC_NAME}} --build-arg GO_VERSION={{.go_version}} --load .
+    silent: true
+  
   _docker/push/all:
-    desc: Push all images to repository.
+    desc: push all images to repository.
     vars:
       REPO_URL: '{{.REPO_URL}}'
 #    deps:
@@ -311,7 +352,11 @@ tasks:
         rm -rf .terraform/ .terraform.lock.hcl terraform.tfstate terraform.tfstate.backup
         terraform init -reconfigure -backend-config=backend_aws.hcl
       fi
-      terraform apply --auto-approve -var="use_localstack={{.LOCALSTACK}}" -var="aws_region={{.REGION}}" -var="arch={{ARCH}}"
+      if [ -z "{{.ARCH}}" ]; then
+        terraform apply --auto-approve -var="use_localstack={{.LOCALSTACK}}" -var="aws_region={{.REGION}}"
+      else
+        terraform apply --auto-approve -var="use_localstack={{.LOCALSTACK}}" -var="aws_region={{.REGION}}" -var="arch={{.ARCH}}"
+      fi
     env:
       AWS_DEFAULT_REGION:      '{{.REGION}}'
       AWS_ACCESS_KEY_ID:       '{{.KEY_ID}}'
@@ -449,6 +494,26 @@ tasks:
           OPENAI_KEY:       'sk-proj-000XXX000'
     silent: true
 
+  env/localstack/platform:
+    desc: Deploy platform to localstack
+    deps:
+      - _localstack/install
+    cmds:
+      - |
+        if [ -z "$LOCALSTACK_AUTH_TOKEN" ]; then
+          echo "Error: LOCALSTACK_AUTH_TOKEN is not set. Please set this environment variable before running LocalStack."
+          exit 1
+        fi
+      - "{{.HOME}}/.pyenv/bin/localstack start -d"
+      - task: _terraform/apply
+        vars:
+          DIR:        "{{.git_root}}/terraform/provisioners/platform"
+          REGION:     us-east-1
+          LOCALSTACK: "true"
+          KEY_ID:     test
+          ACCESS_KEY: test
+    silent: true
+
   env/localstack/stop:
     desc: Remove localstack environment.
     cmds:
@@ -522,4 +587,35 @@ tasks:
             task aws/update_lambda FUNC=$func
           fi
         done
+    silent: true
+
+
+  aws/deploy/monitoring:
+    desc: Deploy to AWS
+    cmds:
+      - |
+        if [ -z "$AWS_DEFAULT_REGION" ]; then
+          echo "Error: AWS_DEFAULT_REGION is not set."
+          exit 1
+        fi
+        if [ -z "$AWS_ACCESS_KEY_ID" ]; then
+          echo "Error: AWS_ACCESS_KEY_ID is not set."
+          exit 1
+        fi
+        if [ -z "$AWS_SECRET_ACCESS_KEY" ]; then
+          echo "Error: AWS_SECRET_ACCESS_KEY is not set."
+          exit 1
+        fi
+        if [ -z "$AWS_ACCOUNT_ID" ]; then
+          echo "Error: AWS_ACCOUNT_ID is not set."
+          exit 1
+        fi
+      - task: _terraform/fmt/check
+      - task: _terraform/apply
+        vars:
+          DIR:        "{{.git_root}}/terraform/provisioners/monitoring"
+          LOCALSTACK: "false"
+          REGION:     '{{.AWS_DEFAULT_REGION}}'
+          KEY_ID:     '{{.AWS_ACCESS_KEY_ID}}'
+          ACCESS_KEY: '{{.AWS_SECRET_ACCESS_KEY}}'
     silent: true
