draft

diff --git a/Taskfile.yaml b/Taskfile.yaml
--- a/Taskfile.yaml
+++ b/Taskfile.yaml
@@ -12,6 +12,7 @@ vars:
   go_fumpt:    latest
   go_outdated: latest
   trivy:       v0.54.1
+  terraform:   1.9.5
   repository_name: lingocards-api
   localstack_ecr_url: "000000000000.dkr.ecr.us-east-1.localhost.localstack.cloud:4566"
 
@@ -168,17 +169,51 @@ tasks:
     silent: true
     internal: true
 
-  _terraform/init:
-    desc: Run 'terraform init'.
+  _terraform/install:
+    desc: Install 'terraform'.
+    cmds:
+      - curl -sL https://releases.hashicorp.com/terraform/{{ .terraform }}/terraform_{{ .terraform }}_{{OS}}_{{ARCH}}.zip -o /tmp/terraform.zip
+      - sudo unzip -o /tmp/terraform.zip -d /usr/local/bin/
+      - sudo chmod a+x /usr/local/bin/terraform
+      - terraform version
+    sources:
+      - /usr/local/bin/terraform
+    silent: true
+    internal: true
+
+  _terraform/plan:
+    desc: Run 'terraform plan'.
     dir: "{{ .DIR }}"
+    deps:
+      - _terraform/install
     cmds:
       - |
-        if [ -z "{{ .KEY_ID }}" ]; then
-          echo "Error: KEY_ID is not set"
+        if [ -z "${LOCALSTACK}" ]; then
+          echo "Error: LOCALSTACK is not set"
           exit 1
         fi
-        if [ -z "{{ .ACCESS_KEY }}" ]; then
-          echo "Error: ACCESS_KEY is not set"
+        if [ -z "${REGION}" ]; then
+          echo "Error: REGION is not set"
+          exit 1
+        fi
+        terraform init -reconfigure
+        terraform plan -var="use_localstack=${LOCALSTACK}" -var="aws_region=${REGION}"
+    env:
+      AWS_DEFAULT_REGION:    '${REGION}'
+      AWS_ACCESS_KEY_ID:     '${KEY_ID}'
+      AWS_SECRET_ACCESS_KEY: '${ACCESS_KEY}'
+    silent: true
+    internal: true
+
+  _terraform/apply:
+    desc: Run 'terraform apply'.
+    dir: "{{ .DIR }}"
+    deps:
+      - _terraform/install
+    cmds:
+      - |
+        if [ -z "{{ .LOCALSTACK }}" ]; then
+          echo "Error: LOCALSTACK is not set"
           exit 1
         fi
         if [ -z "{{ .REGION }}" ]; then
@@ -186,47 +221,6 @@ tasks:
           exit 1
         fi
         terraform init -reconfigure
-    env:
-      AWS_DEFAULT_REGION:    '{{ .REGION }}'
-      AWS_ACCESS_KEY_ID:     '{{ .KEY_ID }}'
-      AWS_SECRET_ACCESS_KEY: '{{ .ACCESS_KEY }}'
-    silent: true
-    internal: true
-
-  _terraform/plan:
-    desc: Run 'terraform plan'.
-    dir: "{{ .DIR }}"
-    cmds:
-      - |
-        if [ -z "{{ .LOCALSTACK }}" ]; then
-          echo "Error: LOCALSTACK is not set"
-          exit 1
-        fi
-        if [ -z "{{ .REGION }}" ]; then
-          echo "Error: REGION is not set"
-          exit 1
-        fi
-        terraform plan -var="use_localstack={{ .LOCALSTACK }}" -var="aws_region={{ .REGION }}"
-    env:
-      AWS_DEFAULT_REGION:    '{{ .REGION }}'
-      AWS_ACCESS_KEY_ID:     '{{ .KEY_ID }}'
-      AWS_SECRET_ACCESS_KEY: '{{ .ACCESS_KEY }}'
-    silent: true
-    internal: true
-
-  _terraform/apply:
-    desc: Run 'terraform apply'.
-    dir: "{{ .DIR }}"
-    cmds:
-      - |
-        if [ -z "{{ .LOCALSTACK }}" ]; then
-          echo "Error: LOCALSTACK is not set"
-          exit 1
-        fi
-        if [ -z "{{ .REGION }}" ]; then
-          echo "Error: REGION is not set"
-          exit 1
-        fi
         terraform apply --auto-approve -var="use_localstack={{ .LOCALSTACK }}" -var="aws_region={{ .REGION }}"
     env:
       AWS_DEFAULT_REGION:    '{{ .REGION }}'
@@ -244,12 +238,6 @@ tasks:
           exit 1
         fi
       - ~/venv/bin/localstack start -d
-      - task: _terraform/init
-        vars: 
-          DIR:        "{{ .git_root }}/terraform/provisioners/infra"
-          REGION:     us-east-1
-          KEY_ID:     test
-          ACCESS_KEY: test
       - task: _terraform/apply
         vars:
           DIR:        "{{ .git_root }}/terraform/provisioners/infra"
@@ -261,12 +249,6 @@ tasks:
       - task: _docker/push/all
         vars:
           REPO_URL: '{{ .localstack_ecr_url }}'
-      - task: _terraform/init
-        vars: 
-          DIR:        "{{ .git_root }}/terraform/provisioners/service"
-          REGION:     us-east-1
-          KEY_ID:     test
-          ACCESS_KEY: test
       - task: _terraform/apply
         vars:
           DIR:        "{{ .git_root }}/terraform/provisioners/service"
